#!/bin/bash

# run container
docker run -it --rm \
	-p 8888:8888 \
	-v $(pwd $1):/home/user:rw \
	da-project \
    jupyter notebook --allow-root --port=8888 --ip=0.0.0.0 --notebook-dir=/home/user/notebooks
